// https://www.bricklink.com/catalogColors.asp?itemType=P&itemNo=3024&v=2
const legoColors = {
    'FFFFFF': {name: 'White', textColor: 'black'},
    'E8E8E8': {name: 'Very Light Gray', textColor: 'black'},
    'E4E8E8': {name: 'Very Light Bluish Gray', textColor: 'black'},
    'AFB5C7': {name: 'Light Bluish Gray', textColor: 'black'},
    '9C9C9C': {name: 'Light Gray', textColor: 'white'},
    '6B5A5A': {name: 'Dark Gray', textColor: 'white'},
    '595D60': {name: 'Dark Bluish Gray', textColor: 'white'},
    '212121': {name: 'Black', textColor: 'white'},
    '6A0E15': {name: 'Dark Red', textColor: 'white'},
    'B30006': {name: 'Red', textColor: 'white'},
    'FF8172': {name: 'Coral', textColor: 'black'},
    'C58D80': {name: 'Sand Red', textColor: 'white'},
    '50372F': {name: 'Dark Brown', textColor: 'white'},
    '6B3F22': {name: 'Brown', textColor: 'white'},
    '99663E': {name: 'Light Brown', textColor: 'white'},
    '82422A': {name: 'Reddish Brown', textColor: 'white'},
    'B89869': {name: 'Dark Tan', textColor: 'black'},
    'EED9A4': {name: 'Tan', textColor: 'black'},
    'FECCB0': {name: 'Light Nougat', textColor: 'black'},
    'FFAF7D': {name: 'Nougat', textColor: 'black'},
    'E3A05B': {name: 'Medium Nougat', textColor: 'black'},
    'B35408': {name: 'Dark Orange', textColor: 'white'},
    'FF7E14': {name: 'Orange', textColor: 'black'},
    'FFA531': {name: 'Medium Orange', textColor: 'black'},
    'FFC700': {name: 'Bright Light Orange', textColor: 'black'},
    'FFBC36': {name: 'Light Orange', textColor: 'black'},
    'FFDCA4': {name: 'Very Light Orange', textColor: 'black'},
    'FFE001': {name: 'Yellow', textColor: 'black'},
    'FFF08C': {name: 'Bright Light Yellow', textColor: 'black'},
    'ECEEBD': {name: 'Light Lime', textColor: 'black'},
    'E7F2A7': {name: 'Yellowish Green', textColor: 'black'},
    'DFE000': {name: 'Medium Lime', textColor: 'black'},
    'C4E000': {name: 'Lime', textColor: 'black'},
    'ABA953': {name: 'Olive Green', textColor: 'black'},
    '2E5543': {name: 'Dark Green', textColor: 'white'},
    '00923D': {name: 'Green', textColor: 'white'},
    '10CB31': {name: 'Bright Green', textColor: 'white'},
    '91DF8C': {name: 'Medium Green', textColor: 'black'},
    'D7EED1': {name: 'Light Green', textColor: 'black'},
    'A2BFA3': {name: 'Sand Green', textColor: 'black'},
    '00A29F': {name: 'Dark Turquoise', textColor: 'white'},
    'CFEFEA': {name: 'Light Aqua', textColor: 'black'},
    '243757': {name: 'Dark Blue', textColor: 'white'},
    '0057A6': {name: 'Blue', textColor: 'white'},
    '009FE0': {name: 'Dark Azure', textColor: 'black'},
    '7DC1D8': {name: 'Maersk Blue', textColor: 'black'},
    '6ACEE0': {name: 'Medium Azure', textColor: 'black'},
    '82ADD8': {name: 'Medium Blue', textColor: 'black'},
    'BCD1ED': {name: 'Bright Light Blue', textColor: 'black'},
    '8899AB': {name: 'Sand Blue', textColor: 'black'},
    '5F2683': {name: 'Dark Purple', textColor: 'white'},
    '7A238D': {name: 'Purple', textColor: 'white'},
    'C689D9': {name: 'Medium Lavender', textColor: 'black'},
    'D3BDE3': {name: 'Lavender', textColor: 'black'},
    'B72276': {name: 'Magenta', textColor: 'white'},
    'EF5BB3': {name: 'Dark Pink', textColor: 'black'},
    'F7BCDA': {name: 'Bright Pink', textColor: 'black'},
    'F5CDD6': {name: 'Pink', textColor: 'black'},
    'F1F2E1': {name: 'Chrome Gold', textColor: 'black'},
    'ACB7C0': {name: 'Pearl Light Gray', textColor: 'black'},
    '8D949C': {name: 'Flat Silver', textColor: 'white'},
    'E79E1D': {name: 'Pearl Gold', textColor: 'black'},
    'C0C0C0': {name: 'Metallic Silver', textColor: 'black'},
};
